[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/2 [idle] active: 
  vault-b/1 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/2 [idle] active: 
  vault-b/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model                 Controller                Cloud/Region        Version  SLA          Timestamp
test-autounseal-wsec  github-pr-1523e-microk8s  microk8s/localhost  3.6.8    unsupported  02:49:20Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             0  10.152.183.186  no       
vault-k8s           active      3  vault-k8s             1  10.152.183.187  no       

Unit          Workload  Agent  Address      Ports  Message
vault-b/0*    active    idle   10.1.63.234         
vault-b/1     active    idle   10.1.63.233         
vault-b/2     active    idle   10.1.63.232         
vault-k8s/0*  active    idle   10.1.63.213         
vault-k8s/1   active    idle   10.1.63.221         
vault-k8s/2   active    idle   10.1.63.220         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-vault-k8s-2: 02:43:17 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1b37ba6c60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:43:19 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa098736d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:43:20 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5ac53350>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:43:20 ERROR unit.vault-k8s/2.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab54742ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:43:21 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed799fb110>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:43:22 ERROR unit.vault-k8s/1.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7febceaf60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:29 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f14c7263440>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:30 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f578553f0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:31 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe77ea6f1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:32 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c4aef8f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:32 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2df3ec5d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:33 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe726743470>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:34 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4b6cfcf50>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:35 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4abcf48fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:35 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5aa073f470>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:36 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe1e0bd0d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:37 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22401411f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:38 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7fe40d340>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:38 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3ed9452ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:39 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbadf737050>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:40 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb1e94d250>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:41 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7ea00fd370>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:42 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71744ee270>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:46:43 ERROR unit.vault-b/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f27b4bfb020>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:43 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4931ef9280>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:46:45 ERROR unit.vault-b/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb2c1cd5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 02:47:47 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6e44e02e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:48:13 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0b9ee1b680>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:48:13 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73b02d75c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 02:48:16 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-wsec.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4fec4e1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:48:27 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-45075aff-5b1f-4709-868d-e307d6b18785: 02:48:27 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 02:48:27 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.63.213:48852->10.152.183.128:17070: write: connection reset by peer: write tcp 10.1.63.213:48852->10.152.183.128:17070: write: connection reset by peer
unit-vault-k8s-1: 02:48:42 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1049 Resetting model test-autounseal-wsec...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1054 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...