[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-kv-requirer-1
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  vault-kv-requirer-b/0 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller                Cloud/Region        Version  SLA          Timestamp
test-kv-ksks  github-pr-12038-microk8s  microk8s/localhost  3.6.8    unsupported  04:06:34Z

App                  Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                     active      3  vault-k8s                     0  10.152.183.33   no       
vault-kv-requirer-a           active      1  vault-kv-requirer             0  10.152.183.66   no       
vault-kv-requirer-b           active      1  vault-kv-requirer             1  10.152.183.233  no       

Unit                    Workload  Agent  Address      Ports  Message
vault-k8s/0*            active    idle   10.1.63.208         
vault-k8s/1             active    idle   10.1.63.217         
vault-k8s/2             active    idle   10.1.63.216         
vault-kv-requirer-a/0*  active    idle   10.1.63.219         
vault-kv-requirer-b/0*  active    idle   10.1.63.221         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 04:02:44 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde856a0050>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 04:02:45 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f800296fb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 04:02:45 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f802487c170>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 04:02:46 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f10f19f3dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 04:02:47 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f441f947ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 04:02:48 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-ksks.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f68bddf3cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 04:05:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-567e3351-af57-4a1f-8986-ae0e1c901209: 04:05:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 04:05:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 04:05:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.63.216:35692->10.152.183.48:17070: write: connection reset by peer: write tcp 10.1.63.216:35692->10.152.183.48:17070: write: connection reset by peer

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-kv-ksks...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-a
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...