[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  s3-integrator/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model             Controller                Cloud/Region        Version  SLA          Timestamp
test-backup-wyvu  github-pr-45d10-microk8s  microk8s/localhost  3.6.8    unsupported  08:11:53Z

App            Version                Status  Scale  Charm          Channel         Rev  Address         Exposed  Message
minio          res:oci-image@220b31a  active      1  minio          ckf-1.9/stable  383  10.152.183.239  no       
s3-integrator                         active      1  s3-integrator  latest/stable   145  10.152.183.130  no       
vault-k8s                             active      3  vault-k8s                        0  10.152.183.112  no       

Unit              Workload  Agent  Address      Ports          Message
minio/0*          active    idle   10.1.63.220  9000-9001/TCP  
s3-integrator/0*  active    idle   10.1.63.212                 
vault-k8s/0*      active    idle   10.1.63.213                 
vault-k8s/1       active    idle   10.1.63.218                 
vault-k8s/2       active    idle   10.1.63.217                 

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 08:09:17 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f23ab9e3e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:09:17 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f32fee040e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:09:18 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c3356b6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:09:19 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7e48bcb8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:09:19 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6671f7da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:09:20 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-backup-wyvu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc3f05ebe30>: Failed to establish a new connection: [Errno 111] Connection refused'))

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-backup-wyvu...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications s3-integrator
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications minio
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...