[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-kv-requirer-1
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller                Cloud/Region        Version  SLA          Timestamp
test-kv-cybj  github-pr-45d10-microk8s  microk8s/localhost  3.6.8    unsupported  08:12:24Z

App                  Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                     active      3  vault-k8s                     0  10.152.183.147  no       
vault-kv-requirer-a           active      1  vault-kv-requirer             0  10.152.183.68   no       
vault-kv-requirer-b           active      1  vault-kv-requirer             1  10.152.183.198  no       

Unit                    Workload  Agent  Address      Ports  Message
vault-k8s/0*            active    idle   10.1.63.209         
vault-k8s/1             active    idle   10.1.63.217         
vault-k8s/2             active    idle   10.1.63.214         
vault-kv-requirer-a/0*  active    idle   10.1.63.219         
vault-kv-requirer-b/0*  active    idle   10.1.63.221         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 08:08:20 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3147a8c080>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:21 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba92573c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:23 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fba1a010080>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:25 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0327a49c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:26 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd99c5801a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:27 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6508b84170>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 08:08:29 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b24f6fb00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:08:32 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f701c67c470>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:08:33 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5898a03f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 08:08:35 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-cybj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efea4fe3da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-8e681cc4-6978-42ec-8ee2-09785e81dbc2: 08:11:10 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 08:11:10 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 08:11:11 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 08:11:26 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.63.217:58636->10.152.183.127:17070: write: connection reset by peer
unit-vault-k8s-2: 08:11:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 08:11:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-8e681cc4-6978-42ec-8ee2-09785e81dbc2: 08:11:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-kv-cybj...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-a
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...