[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model                 Controller                Cloud/Region        Version  SLA          Timestamp
test-autounseal-mcb0  github-pr-a1436-microk8s  microk8s/localhost  3.6.8    unsupported  06:12:08Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             0  10.152.183.200  no       
vault-k8s           active      3  vault-k8s             1  10.152.183.154  no       

Unit          Workload  Agent  Address     Ports  Message
vault-b/0*    active    idle   10.1.98.42         
vault-b/1     active    idle   10.1.98.40         
vault-b/2     active    idle   10.1.98.41         
vault-k8s/0*  active    idle   10.1.98.21         
vault-k8s/1   active    idle   10.1.98.29         
vault-k8s/2   active    idle   10.1.98.28         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 06:06:09 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7848a80c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:06:10 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd80237c7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:06:11 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa9a988c9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:06:12 ERROR unit.vault-k8s/2.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97fe2e4500>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:06:12 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f019cd70aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:06:13 ERROR unit.vault-k8s/1.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd867984a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:17 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5b147dcdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:18 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dac290b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:18 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca933f86b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:19 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0fbd58fef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:20 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6f92125d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:21 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f3c586990>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:21 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea403f5010>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:22 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3395330650>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:22 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff031c1ec60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:24 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bfc80cfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:24 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e6d61e900>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:25 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5216e0980>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:25 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdf05186c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:27 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb74c362ab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:27 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98947791c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:28 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7ca09d45f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:29 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17e501eae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:30 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f27762b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:09:31 ERROR unit.vault-b/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa910814aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:09:32 ERROR unit.vault-b/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f21e67882f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 06:10:35 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48ab41c530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:11:01 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f370d3b6750>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:11:01 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7effbaf2a960>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 06:11:04 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-mcb0.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ce9651a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 06:11:13 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-7fad7691-6760-4cd5-822d-14af504f86a2: 06:11:13 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 06:11:13 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 06:11:15 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.98.29:47424->10.152.183.138:17070: write: connection reset by peer: write tcp 10.1.98.29:47424->10.152.183.138:17070: write: connection reset by peer

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-autounseal-mcb0...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...