[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:762 Adding model github-pr-a1436-microk8s:test-acme-2hvk on cloud microk8s
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-k8s-0
[32mINFO    [0m juju.model:__init__.py:2301 Deploying ch:amd64/noble/self-signed-certificates-263
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  self-signed-certificates/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [allocating] waiting: installing agent
  vault-k8s/1 [allocating] waiting: installing agent
  vault-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [executing] waiting: Waiting for CA certificate to be accessible in the charm
  vault-k8s/1 [allocating] waiting: agent initialising
  vault-k8s/2 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] blocked: Please initialize Vault or integrate with an auto-unseal provider
  vault-k8s/1 [idle] blocked: Please initialize Vault or integrate with an auto-unseal provider
  vault-k8s/2 [idle] blocked: Please initialize Vault or integrate with an auto-unseal provider
[32mINFO    [0m helpers:helpers.py:215 Vault initialized
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.22:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.25:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.24:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] blocked: Please authorize charm (see `authorize-charm` action)
  vault-k8s/2 [idle] blocked: Please authorize charm (see `authorize-charm` action)
[32mINFO    [0m helpers:helpers.py:246 Charm authorized
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [executing] active: 
  vault-k8s/1 [executing] blocked: Please authorize charm (see `authorize-charm` action)
  vault-k8s/2 [executing] blocked: Please authorize charm (see `authorize-charm` action)
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model           Controller                Cloud/Region        Version  SLA          Timestamp
test-acme-2hvk  github-pr-a1436-microk8s  microk8s/localhost  3.6.8    unsupported  06:07:32Z

App                       Version  Status  Scale  Charm                     Channel   Rev  Address         Exposed  Message
self-signed-certificates           active      1  self-signed-certificates  1/stable  263  10.152.183.233  no       
vault-k8s                          active      3  vault-k8s                             0  10.152.183.23   no       

Unit                         Workload  Agent  Address     Ports  Message
self-signed-certificates/0*  active    idle   10.1.98.18         
vault-k8s/0*                 active    idle   10.1.98.22         
vault-k8s/1                  active    idle   10.1.98.25         
vault-k8s/2                  active    idle   10.1.98.24         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 06:05:53 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9a0156ccb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:05:55 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3703374ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:05:55 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fefccff4bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:05:56 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f68ee312090>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:05:56 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f14160148c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:05:58 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-acme-2hvk.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f375ec18530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-self-signed-certificates-0: 06:06:51 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:00 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:02 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:05 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:08 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:13 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 06:07:31 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-acme-2hvk...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...