[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model                 Controller                Cloud/Region        Version  SLA          Timestamp
test-autounseal-umhy  github-pr-a06eb-microk8s  microk8s/localhost  3.6.8    unsupported  02:02:41Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             0  10.152.183.194  no       
vault-k8s           active      3  vault-k8s             1  10.152.183.207  no       

Unit          Workload  Agent  Address     Ports  Message
vault-b/0*    active    idle   10.1.98.41         
vault-b/1     active    idle   10.1.98.42         
vault-b/2     active    idle   10.1.98.40         
vault-k8s/0*  active    idle   10.1.98.21         
vault-k8s/1   active    idle   10.1.98.29         
vault-k8s/2   active    idle   10.1.98.28         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 01:57:04 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb006280ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 01:57:06 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f384ba14a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 01:57:06 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f62187f4980>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 01:57:07 ERROR unit.vault-k8s/2.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f600ba24a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 01:57:08 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7199808c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 01:57:09 ERROR unit.vault-k8s/1.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd9bf3fcbf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 01:59:55 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1f09f8d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 01:59:57 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f67ca61c8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 01:59:59 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5195f7e330>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:00 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f24f2a7cbc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:00 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d5a6fd0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:01 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4496d7d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:02 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb042d7a990>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:03 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e3e3f6a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:03 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f970aa106b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:04 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9778ee10a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:05 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6cb5f69f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:06 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f199db86c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:06 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd1bfa20d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:07 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36f4578ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:08 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fc2dfad50>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:09 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdfc58129f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:00:09 ERROR unit.vault-b/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab10af2630>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:10 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feae76f9010>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:11 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe6ba162510>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 02:00:13 ERROR unit.vault-b/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa55747a6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 02:00:56 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8cf0700500>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 02:01:23 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ad95ba2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 02:01:39 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-umhy.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78ce26b6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 02:01:39 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-e95f49b6-d089-47d8-83e1-b000c27f5177: 02:01:39 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 02:01:40 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 02:01:56 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-autounseal-umhy...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...