[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.16:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.25:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.98.24:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] blocked: Please unseal Vault
  vault-k8s/1 [idle] blocked: Please unseal Vault
  vault-k8s/2 [idle] blocked: Please unseal Vault
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model           Controller                Cloud/Region        Version  SLA          Timestamp
test-core-r5ym  github-pr-76763-microk8s  microk8s/localhost  3.6.8    unsupported  02:48:26Z

App                       Version  Status  Scale  Charm                     Channel   Rev  Address         Exposed  Message
self-signed-certificates           active      1  self-signed-certificates  1/stable  317  10.152.183.88   no       
vault-k8s                          active      3  vault-k8s                             0  10.152.183.184  no       

Unit                         Workload  Agent  Address     Ports  Message
self-signed-certificates/0*  active    idle   10.1.98.31         
vault-k8s/0*                 active    idle   10.1.98.16         
vault-k8s/1                  active    idle   10.1.98.25         
vault-k8s/2                  active    idle   10.1.98.24         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-1: 02:40:25 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f746f37c7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:40:26 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe3cab58080>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:40:27 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff6e5f4b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:40:28 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8857a20b00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:40:28 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff998d41d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:40:29 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc9f5a043b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 02:41:41 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33f74ae780>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 02:42:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.98.24:42886->10.152.183.44:17070: write: connection reset by peer
model-cc936af9-a1ec-4067-8584-0f8211d6a6a8: 02:42:26 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 02:42:31 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-3: 02:43:17 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e4737ce00>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 02:43:18 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f858c814b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 02:43:20 ERROR unit.vault-k8s/3.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-r5ym.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff1a0862630>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-self-signed-certificates-0: 02:45:12 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-vault-k8s-1: 02:45:13 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-cc936af9-a1ec-4067-8584-0f8211d6a6a8: 02:45:15 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 02:45:15 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 02:45:15 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 02:47:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 02:47:57 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 02:48:15 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-core-r5ym...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...