[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.63.209:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.63.217:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m vault_helpers:vault_helpers.py:94 Unsealed vault unit: https://10.1.63.215:8200.
[32mINFO    [0m vault_helpers:vault_helpers.py:76 Vault unit is unsealed.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] blocked: Please unseal Vault
  vault-k8s/1 [idle] blocked: Please unseal Vault
  vault-k8s/2 [idle] blocked: Please unseal Vault
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model           Controller                Cloud/Region        Version  SLA          Timestamp
test-core-nvnu  github-pr-21f4a-microk8s  microk8s/localhost  3.6.8    unsupported  04:05:59Z

App                       Version  Status  Scale  Charm                     Channel   Rev  Address         Exposed  Message
self-signed-certificates           active      1  self-signed-certificates  1/stable  317  10.152.183.233  no       
vault-k8s                          active      3  vault-k8s                             0  10.152.183.211  no       

Unit                         Workload  Agent  Address      Ports  Message
self-signed-certificates/0*  active    idle   10.1.63.223         
vault-k8s/0*                 active    idle   10.1.63.209         
vault-k8s/1                  active    idle   10.1.63.217         
vault-k8s/2                  active    idle   10.1.63.215         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 03:57:53 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faeca55d610>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 03:57:54 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faabe300620>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 03:57:55 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f25d368c590>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 03:57:56 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd7b37fca10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 03:57:56 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac1f4f88f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 03:57:58 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b16424530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 03:59:08 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff367b6960>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 03:59:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-700f52f1-1d0d-4226-84d4-e2e78f8e4fe0: 03:59:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 03:59:55 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-3: 04:00:43 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc1f75f4a40>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 04:00:45 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa33e2f8b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 04:00:46 ERROR unit.vault-k8s/3.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-nvnu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8365bc8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-0: 04:01:10 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-700f52f1-1d0d-4226-84d4-e2e78f8e4fe0: 04:01:10 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 04:01:45 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 04:02:12 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 04:02:48 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 04:02:51 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
model-700f52f1-1d0d-4226-84d4-e2e78f8e4fe0: 04:02:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 04:02:52 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 04:03:58 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 04:03:58 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 04:04:14 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-vault-k8s-2: 04:04:16 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 04:04:28 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 04:05:31 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-700f52f1-1d0d-4226-84d4-e2e78f8e4fe0: 04:05:31 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-core-nvnu...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...